apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
  annotations:
      metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  ports:
  - port: 21
    targetPort: 21
    name: ftp
  - port: 31110
    name: p1
  - port: 31111
    name: p2
  selector:
    app: ftps
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ftps
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ftps
    template:
      metadata:
        labels:
          app: ftps
      spec:
        containers:
        - name: ftps
          image: ftps
          imagePullPolicy: Never
          ports:
            - containerPort: 21
            - containerPort: 31110
            - containerPort: 31111
          livenessProbe:
              exec:
                command:
                - sh
                - /health.sh
              initialDelaySeconds: 5
              periodSeconds: 3