apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  type: ClusterIP
  ports:
  - port: 8086
    targetPort: 8086
    name: influxdb
  selector:
    app: influxdb
  clusterIP: 10.107.84.224
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: influxdb
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: influxdb
    template:
      metadata:
        labels:
          app: influxdb
      spec:
        containers:
        - name: influxdb
          image: influxdb
          imagePullPolicy: Never
          ports:
            - containerPort: 8086
          volumeMounts:
            - mountPath: "/var/lib/influxdb/data"
              name: influxdb
            - mountPath: "/var/run/docker.sock"
              name: docker-sock
          livenessProbe:
              exec:
                command:
                - sh
                - /health.sh
              initialDelaySeconds: 5
              periodSeconds: 3
        volumes:
        - name: influxdb
          persistentVolumeClaim:
            claimName: influxdb
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock