apiVersion: v1
kind: Service
metadata:
  name: my-pma
  labels:
    app: my-pma
  annotations:
      metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
    name: pma
  selector:
    app: my-pma
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: my-pma
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: my-pma
    template:
      metadata:
        labels:
          app: my-pma
      spec:
        containers:
        - name: my-pma
          image: my-pma
          imagePullPolicy: Never
          ports:
            - containerPort: 5000

# kubectl apply -f <path-to-yaml-file>