apiVersion: v1
kind: Service
metadata:
  name: my-wp
  labels:
    app: my-wp
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  ports:
  - port: 5050
    targetPort: 5050
    name: wp
  selector:
    app: my-wp
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: my-wp
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: my-wp
    template:
      metadata:
        labels:
          app: my-wp
      spec:
        containers:
        - name: my-wp
          image: my-wp
          imagePullPolicy: Never
          ports:
            - containerPort: 5050

# kubectl apply -f <path-to-yaml-file>