apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  ports:
  - port: 5050
    targetPort: 5050
    name: wordpress
  selector:
    app: wordpress
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: wordpress
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: wordpress
    template:
      metadata:
        labels:
          app: wordpress
      spec:
        containers:
        - name: wordpress
          image: wordpress
          imagePullPolicy: Never
          ports:
            - containerPort: 5050
          livenessProbe:
              exec:
                command:
                - sh
                - /health.sh
              initialDelaySeconds: 5
              periodSeconds: 5